# Change these first
owner: wesreckless # Your GitHub organization or username, where this repository lives
repo: upptime-ams # The name of this repository

sites:
  - name: AMS
    url: https://www.amsmobilesolutions.cl
  - name: Sentraland
    url: https://www.sentraland.net
  - name: Soporte Sentraland
    url: https://soporte.sentraland.net
  - name: PST Sentraland
    url: https://sent.sentraland.net
  - name: PST Netuno
    url: https://smsys.netuno.cl
  - name: PST Movistar
    url: https://pst.movistar.cl:8443/PSTadmin/init.do
  - name: Convenios La Araucana
    url: https://convenios.laaraucana.cl
  - name: Essbio
    url: https://www.essbio.cl
  - name: Nuevosur
    url: https://www.nuevosur.cl
  - name: Club Metrogas
    url: https://www.clubmetrogas.cl
  - name: backcore.sentraland.net
    url: https://backcore.sentraland.net
  - name: hospitalario.sentraland.net
    url: https://hospitalario.sentraland.net
  - name: programas-medicos.sentraland.net
    url: https://programas-medicos.sentraland.net
  - name: subsidios.sentraland.net
    url: https://subsidios.sentraland.net
  - name: www.aconcaguatravel.cl
    url: https://www.aconcaguatravel.cl


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime-ams
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
